services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn recipes_project.wsgi"
    healthCheckPath: "/"
    region: oregon
