# Generated by Django 5.1.3 on 2025-02-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Our Platform!', max_length=200)),
                ('hero_description', models.TextField(default='We’re thrilled to have you join our vibrant community of food lovers, home cooks, and culinary explorers. Whether you’re here to share your favorite recipes, discover new flavors, or connect with fellow food enthusiasts, your journey to culinary greatness starts here.')),
                ('hero_button_text', models.CharField(default='Get Started', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing_page/')),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_description', models.TextField(default='At ShareRecipe, we’re passionate about bringing people together through the joy of cooking. Our mission is to create a welcoming space where food lovers can share, discover, and celebrate recipes from around the world. Whether you’re a seasoned chef or a kitchen newbie, we’re here to inspire your culinary journey.')),
                ('feature_title', models.CharField(default='Our Features', max_length=200)),
                ('features', models.TextField(default='✨ High Quality: We prioritize excellence in every aspect, from user-friendly tools to a diverse collection of recipes, ensuring a top-notch experience for all.\n💰 Affordable Pricing: Enjoy access to premium features without breaking the bank.\n⏰ 24/7 Support: Our dedicated team is always here to assist you, day or night.')),
            ],
        ),
    ]
