# Generated by Django 5.1.3 on 2025-02-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_landingpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='features',
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='features',
            field=models.ManyToManyField(blank=True, to='recipes.feature'),
        ),
    ]
