# Generated by Django 5.1.3 on 2025-02-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_feature_remove_landingpagecontent_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='features',
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
