# Generated by Django 5.1.3 on 2025-02-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_landingpagecontent_features_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='features',
        ),
    ]
