# Generated by Django 5.1.3 on 2025-02-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_delete_feature_remove_landingpagecontent_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='posted_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
